### ISSUE TITLE
Why llvm-spirv has to be in /usr/bin?

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#110]
Why not having it in PATH suffice?

**Comment by franz** [comment]
It doesn't have to be in `/usr/bin`; it has to be in the same path as the Clang binary used to compile CHIP-SPV. Same applies for llvm-link, opt and other binaries used by CHIP-SPV. Why not PATH: because using just PATH could pick up any other random build or version of llvm-spirv (or other tools), which then might not work - all of these tools are LLVM-version-dependent. But we could add a cmake option for user to specify exact llvm-spirv.

**Comment by pjaaskel** [comment]
OK, yes, makes sense to have at least an cmake option.

**Comment by linehill** [comment]
Clang does search llvm-spirv from PATH. At least it works on my machine with Clang 14 and 15.

**Comment by linehill** [comment]
BTW, there is a hazard that the Clang may find a llvm-spirv which links to a LLVM version different from the Clang. I made a patch ([seek-versioned-llvm-spirv.zip](https://github.com/CHIP-SPV/chip-spv/files/9359009/seek-versioned-llvm-spirv.zip)) for Clang which changes it to lookup `llvm-spirv-<llvm-major-version>` first and then the `llvm-spirv`. This requires that the distributed, correct version of the llvm-spirv is either renamed to llvm-spirv-XX for clang-XX or a symlink, llvm-spirv-XX, pointing to the correct llvm-spirv is put into the PATH.
