### ISSUE TITLE
[bitcode library] __powf causes kernel linking error

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#77]
on branch #76, `floatMath.cc`

````
   // Issue here
   Out[tid] = __powf(2.0f, Out[tid]);
````

leaving this uncommented causes the kernel build to fail with `ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED`

**Comment by franz** [comment]
The code in the ocml branch is *almost* correct,  only a few issues:

1) there is no `native_pow` in OpenCL, only `native_powr`. The latter has a limitation on argument range (x >= 0). Actually [CUDA programming guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#intrinsic-functions) says that `__powf` is implemented as `exp2f(y * __log2f(x))`. so i think that should be done instead of using `native_powr`.

2) it's missing the corresponding `native_powr` in `bitcode/mathlib.cl`

you can take a look in the commit above.
