### ISSUE TITLE
Strip/hide failing tests from the test suite

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#95]
For a release, it is important to have a test suite which has only tests that should always pass. This is for the user to check that the build was solid. Currently there seems to be some failing tests and it's not clear are they expected to fail (sometimes) or it's due to a broken/unsupported local setup.

**Comment by pjaaskel** [comment]
Could be fixable by marking the unstable or known failing tests with a label such as 'flaky_test' and then in README.md instruct the end user to skip then with ```ctest -LE flaky_test```.

**Comment by franz** [comment]
Should be fixed in PR #113; The internal failing tests are disabled by default and are never run (they can be re-enabled with `ENABLE_FAILING_TESTS` cmake option). The external tests (like HIP testsuite) can't be disabled that way, so instead there is a new make target `check` which only runs the passing tests (~608 at the moment).

**Comment by pvelesko** [comment]
So far I've seen only 2 tests disabled - callback tests and those should not be disabled. 
Instead, we should mark known failures such as tests for hipGraph, hipStreamPerThread, hipOccupancy, etc.
